### PR TITLE
query selector ignore video preview + refactor image checking function

### PR DESCRIPTION
**Pull request by ryantanrk**
the query selector now only covers regular video thumbnails and **not** the video preview that appears when hovered

~~currently the mrbeast overlay appears before the thumbnail itself, i think that it should appear only after the thumbnail is loaded~~ **edit: this is causing issues on firefox so has been rolled back**

also refactored the recursive image checking function. i would suggest to not put functions inside of functions, to keep it simple

result:

https://github.com/MagicJinn/MrBeastify-Youtube/assets/49902829/cb2fb086-fa55-4ff0-ae5a-004180cb1aa0

### CODE REVIEW

**Comment by MagicJinn** [comment]
Hey there! ~~Unfortunately, I'm having trouble recreating the effect in the video. When I load the addon for debugging I still have the same effect when video previews start playing.~~ I can recreate the effect on Edge, but not on Chrome. Might be because youtube uses different tags for different platforms and devices?

I'll merge this with the main branch soon regardless, since fixing this for 2 browsers is still very good and better than nothing :)

**Comment by ryantanrk** [comment]
i'll try again on chrome, i remember it was working just fine there

**Comment by ryantanrk** [comment]
my query selector was not selecting thumbnails in the recommended sidebar, my mistake, fixed

**Comment by MagicJinn** [comment]
Hey there! Turns out I was being a big dum dum and was running 2 versions of the addon at the same time. Now with the correct one running, this in fact does work for chrome. Thanks for the contribution, I will merge it soon!

**Pull request merged**
